# fly.toml app configuration file generated for glory-presenter-java on 2023-12-05T10:07:16-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "glory-presenter-java"
primary_region = "dfw"

# swap_size_mb = 512

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
