# Define the root logger with console and inmemory appender
log4j.rootLogger = DEBUG, CONSOLE, INMEMORY

# Define the console appender
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.conversionPattern=%m%n

# Define the inmemory appender
log4j.appender.INMEMORY=com.scottmo.ui.utils.InMemoryAppender
log4j.appender.INMEMORY.layout=org.apache.log4j.PatternLayout
log4j.appender.INMEMORY.layout.conversionPattern=%m%n
